# docker-compose
services:
  backend:
    build:
      context: ./backend
    container_name: kms_backend
    env_file:
      - ./backend/.env.production
    volumes:
      - ./backend/.env.production:/app/.env.production
    ports:
      - "4000:4000"
    depends_on:
      - redis
    networks:
      - kms-network

  frontend:
    build:
      context: ./frontend
    container_name: kms_frontend
    env_file:
      - ./frontend/.env.production
    volumes:
      - ./frontend/.env.production:/app/.env.production
    ports:
      - "80:80"
    networks:
      - kms-network
