FROM node:20-alpine

WORKDIR /app
COPY frontend/ ./
RUN npm install && npm run build

# Serve bằng nginx
FROM nginx:alpine
COPY --from=0 /app/dist /usr/share/nginx/html
COPY ./frontend/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
